/* THIS (.ts) FILE IS GENERATED BY TypedSignalR.Client.TypeScript */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import type { IStreamResult, Subject } from '@microsoft/signalr';
import type { JoinSessionDto, RestoreStateDto, ParticipantUpdateDto, SubmitAnswerDto, ParticipantDto, ParticipantUpdateResponseDto, QuestionTemplateDto, AnswerDisplayDto } from '../Backend.Dto';
import type { SessionState } from '../Backend.Models.Enums';

export type ISessionHub = {
    /**
    * @param data Transpiled from Backend.Dto.JoinSessionDto
    * @returns Transpiled from System.Threading.Tasks.Task<Backend.Dto.RestoreStateDto?>
    */
    joinSession(data: JoinSessionDto): Promise<RestoreStateDto>;
    /**
    * @param roomCode Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    leaveRoom(roomCode: string): Promise<void>;
    /**
    * @param data Transpiled from Backend.Dto.ParticipantUpdateDto
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    updateParticipantData(data: ParticipantUpdateDto): Promise<boolean>;
    /**
    * @param roomCode Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    startSession(roomCode: string): Promise<boolean>;
    /**
    * @param roomCode Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    nextQuestion(roomCode: string): Promise<boolean>;
    /**
    * @param roomCode Transpiled from string
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    closeSession(roomCode: string): Promise<boolean>;
    /**
    * @param data Transpiled from Backend.Dto.SubmitAnswerDto
    * @returns Transpiled from System.Threading.Tasks.Task<bool>
    */
    submitAnswer(data: SubmitAnswerDto): Promise<boolean>;
}

export type ISessionHubClient = {
    /**
    * @param data Transpiled from Backend.Dto.ParticipantDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    participantJoined(data: ParticipantDto): Promise<void>;
    /**
    * @param data Transpiled from Backend.Dto.ParticipantUpdateResponseDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    participantUpdated(data: ParticipantUpdateResponseDto): Promise<void>;
    /**
    * @param newState Transpiled from Backend.Models.Enums.SessionState
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    sessionStateChanged(newState: SessionState): Promise<void>;
    /**
    * @param data Transpiled from Backend.Dto.QuestionTemplateDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    questionChanged(data: QuestionTemplateDto): Promise<void>;
    /**
    * @param data Transpiled from Backend.Dto.AnswerDisplayDto
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    answerSubmitted(data: AnswerDisplayDto): Promise<void>;
    /**
    * @returns Transpiled from System.Threading.Tasks.Task
    */
    sessionClosed(): Promise<void>;
}

